# Generated by Django 3.1.4 on 2021-03-17 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0022_remove_optionsymbol_optionsportfolio'),
        ('accounts', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('optionsymbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option_pricing.optionsymbol')),
                ('portfolio', models.ManyToManyField(blank=True, default=None, related_name='optionsportfolio', to='accounts.Portfolio')),
            ],
        ),
    ]
