# Generated by Django 3.1.4 on 2021-03-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210319_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliooption',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliooption',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
