# Generated by Django 3.1.4 on 2021-03-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210321_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliooption',
            name='position',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default='Long', max_length=5),
        ),
    ]
