# Generated by Django 3.1.4 on 2021-03-29 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210328_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliofuture',
            name='buysellprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliofuture',
            name='contracts',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliofuture',
            name='position',
            field=models.CharField(choices=[('Long', 'Long'), ('Short', 'Short')], default='Long', max_length=5),
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='buyprice',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfoliofuture',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliofuture',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='portfoliostock',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
