# Generated by Django 3.1.4 on 2020-12-27 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Optionsymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('asset', models.CharField(choices=[('FTSE', 'FTSE'), ('ALPHA', 'ALPHA'), ('HTO', 'OTE'), ('ETE', 'ETE'), ('OPAP', 'OPAP'), ('PPC', 'DEH'), ('TPEIR', 'PEIRAIOS')], max_length=5)),
                ('optiontype', models.CharField(choices=[('c', 'Call'), ('p', 'Put')], max_length=1)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expmonthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('closing_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('max', models.DecimalField(decimal_places=3, max_digits=8)),
                ('min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trades', models.IntegerField()),
                ('fixing_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('open_interest', models.IntegerField()),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imp_vol', models.DecimalField(decimal_places=3, max_digits=8)),
                ('atm_strike', models.DecimalField(decimal_places=3, max_digits=8)),
                ('frontexpdate', models.DateField()),
                ('expmonth_atm_impvol', models.DecimalField(decimal_places=3, max_digits=8)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('theta', models.DecimalField(decimal_places=3, max_digits=8)),
                ('gamma', models.DecimalField(decimal_places=3, max_digits=8)),
                ('vega', models.DecimalField(decimal_places=3, max_digits=8)),
                ('optionsymbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option_pricing.optionsymbol')),
            ],
        ),
    ]
