# Generated by Django 3.1.4 on 2021-01-01 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('option_pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsymbol',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='optionsymbol',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
    ]
