# Generated by Django 3.1.4 on 2021-01-03 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('option_pricing', '0003_remove_optionsymbol_like_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsymbol',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
