# Generated by Django 3.1.4 on 2021-01-03 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('option_pricing', '0004_optionsymbol_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsymbol',
            name='optionscreeners',
            field=models.ManyToManyField(blank=True, default=None, related_name='optionscreeners', to=settings.AUTH_USER_MODEL),
        ),
    ]
