# Generated by Django 3.1.4 on 2021-01-08 22:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('option_pricing', '0005_optionsymbol_optionscreeners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futuresymbol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('asset', models.CharField(choices=[('ADMIE', 'ADMIE'), ('ALPHA', 'ALPHA'), ('BELA', 'JUMBO'), ('CENER', 'CENERGY'), ('EEE', 'COCA-COLA'), ('ELLAK', 'ELLAKTOR'), ('ELPE', 'ELPE'), ('ETE', 'ETE'), ('EUROB', 'EUROB'), ('EXAE', 'EXAE'), ('EYDAP', 'EYDAP'), ('FOYRK', 'FOURLIS'), ('FTSE', 'FTSE'), ('GEKTE', 'GEKTERNA'), ('HTO', 'OTE'), ('INTRK', 'INTRACOM'), ('LAMDA', 'LAMDA'), ('MIG', 'MIG'), ('MOH', 'MOTOR OIL'), ('MYTIL', 'MYTIL'), ('OPAP', 'OPAP'), ('PPA', 'OLP'), ('PPC', 'DEH'), ('TATT', 'ATTICA BANK'), ('TENER', 'TERNA ENERGY'), ('TITC', 'TITAN'), ('TPEIR', 'PEIRAIOS'), ('VIO', 'VIOHALCO')], max_length=5)),
                ('expmonthdate', models.DateField()),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite_future', to=settings.AUTH_USER_MODEL)),
                ('futurescreeners', models.ManyToManyField(blank=True, default=None, related_name='futurescreeners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
