# Generated by Django 3.1.4 on 2021-01-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0006_futuresymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('closing_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.IntegerField()),
                ('max', models.DecimalField(decimal_places=3, max_digits=8)),
                ('min', models.DecimalField(decimal_places=3, max_digits=8)),
                ('trades', models.IntegerField()),
                ('fixing_price', models.DecimalField(decimal_places=3, max_digits=8)),
                ('open_interest', models.IntegerField()),
                ('stock', models.DecimalField(decimal_places=2, max_digits=8)),
                ('futuresymbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='option_pricing.futuresymbol')),
            ],
        ),
    ]
