# Generated by Django 3.1.4 on 2021-01-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0007_future'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=15)),
                ('asset', models.CharField(choices=[('ADMIE', 'ADMIE'), ('ALPHA', 'ALPHA'), ('BELA', 'JUMBO'), ('CENER', 'CENERGY'), ('EEE', 'COCA-COLA'), ('ELLAKTOR', 'ELLAKTOR'), ('ELPE', 'ELPE'), ('ETE', 'ETE'), ('EUROB', 'EUROB'), ('EXAE', 'EXAE'), ('EYDAP', 'EYDAP'), ('FOYRK', 'FOURLIS'), ('FTSE', 'FTSE'), ('GEKTERNA', 'GEKTERNA'), ('HTO', 'OTE'), ('INTRK', 'INTRACOM'), ('LAMDA', 'LAMDA'), ('MIG', 'MIG'), ('MOH', 'MOTOR OIL'), ('MYTIL', 'MYTIL'), ('OPAP', 'OPAP'), ('PPA', 'OLP'), ('PPC', 'DEH'), ('TATT', 'ATTICA BANK'), ('TENERGY', 'TERNA ENERGY'), ('TITC', 'TITAN'), ('TPEIR', 'PEIRAIOS'), ('VIO', 'VIOHALCO')], max_length=10)),
                ('date', models.DateTimeField()),
                ('high', models.DecimalField(decimal_places=3, max_digits=8)),
                ('low', models.DecimalField(decimal_places=3, max_digits=8)),
                ('open', models.DecimalField(decimal_places=3, max_digits=8)),
                ('close', models.DecimalField(decimal_places=3, max_digits=8)),
                ('volume', models.FloatField()),
            ],
        ),
    ]
