# Generated by Django 3.1.4 on 2021-02-08 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0011_optionseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsymbol',
            name='optionseries',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='option_pricing.optionseries'),
            preserve_default=False,
        ),
    ]
