# Generated by Django 3.1.4 on 2021-02-09 09:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('option_pricing', '0012_optionsymbol_optionseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionseries',
            name='seriesscreeners',
            field=models.ManyToManyField(blank=True, default=None, related_name='seriesscreeners', to=settings.AUTH_USER_MODEL),
        ),
    ]
