# Generated by Django 3.1.4 on 2021-02-13 16:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('option_pricing', '0013_optionseries_seriesscreeners'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionseries',
            name='seriesatmscreeners',
            field=models.ManyToManyField(blank=True, default=None, related_name='seriesatmscreeners', to=settings.AUTH_USER_MODEL),
        ),
    ]
