# Generated by Django 3.1.4 on 2021-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0015_optionvolume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionvolume',
            name='date',
            field=models.DateField(),
        ),
    ]
