# Generated by Django 3.1.4 on 2021-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0016_auto_20210222_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optionvolumeaggseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset', models.CharField(choices=[('FTSE', 'FTSE'), ('ALPHA', 'ALPHA'), ('HTO', 'OTE'), ('ETE', 'ETE'), ('OPAP', 'OPAP'), ('PPC', 'DEH'), ('TPEIR', 'PEIRAIOS')], max_length=5)),
                ('optiontype', models.CharField(choices=[('c', 'Call'), ('p', 'Put')], max_length=1)),
                ('volume', models.IntegerField()),
                ('trades', models.IntegerField()),
                ('open_interest', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Optionvolumeaggseriesasset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('optiontype', models.CharField(choices=[('c', 'Call'), ('p', 'Put')], max_length=1)),
                ('volume', models.IntegerField()),
                ('trades', models.IntegerField()),
                ('open_interest', models.IntegerField()),
            ],
        ),
    ]
