# Generated by Django 3.1.4 on 2021-03-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0017_optionvolumeaggseries_optionvolumeaggseriesasset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optioncallputmonthlyratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sum_vol_calls', models.IntegerField()),
                ('sum_vol_puts', models.IntegerField()),
                ('callputratio', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
