# Generated by Django 3.1.4 on 2021-03-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0019_auto_20210303_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Futurevolumeaggasset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('asset', models.CharField(max_length=5)),
                ('volume', models.IntegerField()),
                ('open_interest', models.IntegerField()),
            ],
        ),
    ]
