# Generated by Django 3.1.4 on 2021-03-16 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_portfolio'),
        ('option_pricing', '0020_futurevolumeaggasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionsymbol',
            name='optionsportfolio',
            field=models.ManyToManyField(blank=True, default=None, related_name='optionsportfolio', to='accounts.Portfolio'),
        ),
    ]
