# Generated by Django 3.1.4 on 2021-03-17 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0021_optionsymbol_optionsportfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionsymbol',
            name='optionsportfolio',
        ),
    ]
