# Generated by Django 3.2.5 on 2021-08-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0028_auto_20210814_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='delta',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='option',
            name='gamma',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='option',
            name='theta',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='option',
            name='vega',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
