# Generated by Django 3.2.5 on 2021-10-02 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0030_optionseries_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 23, 977121)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurecsv',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 36, 982094)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futuresymbol',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 40, 309309)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='futurevolumeaggasset',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 43, 195778)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 46, 911536)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optioncallputmonthlyratio',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 51, 581740)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optioncsv',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 10, 57, 164406)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionsymbol',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 11, 1, 864803)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionvolume',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 11, 4, 898926)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionvolumeaggseries',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 11, 8, 296919)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionvolumeaggseriesasset',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 11, 11, 711211)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 11, 14, 896923)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksymbol',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 10, 1, 14, 11, 17, 755114)),
            preserve_default=False,
        ),
    ]
