# Generated by Django 3.2.5 on 2021-10-02 11:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0031_auto_20211002_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioncsv',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 2, 14, 55, 3, 883060)),
        ),
    ]
