# Generated by Django 3.2.5 on 2021-10-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0032_alter_optioncsv_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='future',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='futurecsv',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='futurevolumeaggasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='option',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optioncallputmonthlyratio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optioncsv',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optionvolume',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optionvolumeaggseries',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optionvolumeaggseriesasset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='created_at',
        ),
    ]
