# Generated by Django 3.2.5 on 2021-10-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0033_auto_20211002_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='futuresymbol',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optionseries',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='optionsymbol',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='stocksymbol',
            name='created_at',
        ),
    ]
