# Generated by Django 3.2.5 on 2021-10-08 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('option_pricing', '0034_auto_20211002_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='futuresymbol',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 22, 56, 31, 9281)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionseries',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 22, 57, 9, 338648)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='optionsymbol',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 22, 57, 28, 569161)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocksymbol',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 22, 57, 35, 735898)),
            preserve_default=False,
        ),
    ]
